### ISSUE TITLE
when running tokens.js it throws an error see below

### ISSUE THREAD

**Issue by zalmyr** [amper5and/voice.js#21]
node .\tokens.js "email@gmail.com" "password"
.rnr error:  { [GoogleVoiceError: LOGIN_ERROR]
  code: 1,
  message: 'LOGIN_ERROR',
  details:
   { [Error: Login failed]
     data: 'https://developers.google.com/accounts/docs/AuthForInstalledApps\n',
     response:
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        socket: [Object],
        connection: [Object],
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        trailers: {},
        _pendings: [],
        _pendingIndex: 0,
        url: '',
        method: null,
        statusCode: 404,
        client: [Object],
        _consuming: true,
        _dumped: false,
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        upgrade: false,
        req: [Object],
        pipe: [Function],
        addListener: [Function: addListener],
        on: [Function: addListener],
        pause: [Function],
        resume: [Function],
        read: [Function] } } }
.gvx error:  { [GoogleVoiceError: LOGIN_ERROR]
  code: 1,
  message: 'LOGIN_ERROR',
  details:
   { [Error: Login failed]
     data: 'https://developers.google.com/accounts/docs/AuthForInstalledApps\n',
     response:
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        socket: [Object],
        connection: [Object],
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        trailers: {},
        _pendings: [],
        _pendingIndex: 0,
        url: '',
        method: null,
        statusCode: 404,
        client: [Object],
        _consuming: true,
        _dumped: false,
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        upgrade: false,
        req: [Object],
        pipe: [Function],
        addListener: [Function: addListener],
        on: [Function: addListener],
        pause: [Function],
        resume: [Function],
        read: [Function] } } }
.auth error:  { [GoogleVoiceError: LOGIN_ERROR]
  code: 1,
  message: 'LOGIN_ERROR',
  details:
   { [Error: Login failed]
     data: 'https://developers.google.com/accounts/docs/AuthForInstalledApps\n',
     response:
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        socket: [Object],
        connection: [Object],
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        trailers: {},
        _pendings: [],
        _pendingIndex: 0,
        url: '',
        method: null,
        statusCode: 404,
        client: [Object],
        _consuming: true,
        _dumped: false,
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        upgrade: false,
        req: [Object],
        pipe: [Function],
        addListener: [Function: addListener],
        on: [Function: addListener],
        pause: [Function],
        resume: [Function],
        read: [Function] } } }

**Comment by ashwinks** [comment]
Same here, looks like Google changed something.

**Comment by zalmyr** [comment]
https://developers.google.com/identity/protocols/AuthForInstalledApps 

(Pasted from the link above)
Important: ClientLogin has been officially deprecated since April 20, 2012 and is now no longer available. Requests to ClientLogin will fail with a HTTP 404 response. We encourage you to migrate to OAuth 2.0 as soon as possible.


Work around create a file tokens.json
login to Google Voice and export the "gv" cookie add it as the value of "auth" in the json.

for the "rnr" on the Google Voice page "View Source" search fro "_rnr_se"  use the value for the "rnr"

{"auth":"DQAAAAcBAACI5Q85-...................................","rnr":"______________________"}

**Comment by ashwinks** [comment]
How do we use that tokens.json file to make requests?

**Comment by amper5and** [comment]
ClientLogin deprecation has been in the works for a long time. Please feel free to contribute to an oauth alternative!

**Comment by jpca999** [comment]
@zalmyr  your technique doesnt work, it throws same/ similar error even after manually adding the file with the parameters.

**Comment by suan** [comment]
@jpca999 Curious Did you ever manage to get this working?
